version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: happymysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./happy.cnf:/etc/mysql/conf.d/mysql_additional.cnf
      - ./db:/var/lib/mysql
    ports:
      - ${MYSQL_EXTERNAL_PORT}:3306
    networks:
      - happy-network
    deploy: 
      resources: 
        limits:
          cpus: '${CPUS_CONTAINER_LIMIT}'
          memory: '${MEMORY_CONTAINER_LIMIT}'

networks: 
  happy-network:
    driver: bridge